<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE committee [
  <!ELEMENT committee (name, countries, GSLtime?, topics) >
  <!ELEMENT name (#PCDATA) >
  <!ELEMENT countries (country+) > 
  <!ELEMENT country (countryname?,code,observer?) >
  <!ELEMENT countryname (#PCDATA) >
  <!ELEMENT code (#PCDATA) >
  <!ELEMENT observer (#PCDATA) >
  <!ELEMENT GSLtime (#PCDATA) >
  <!ELEMENT topics (topic+) >
  <!ELEMENT topic (topicname) >
  <!ELEMENT topicname (#PCDATA) >
]>
<committee>
	<name>Security Council</name>
	<countries>
		<country>
			<countryname>Belgium</countryname>
			<code>BELG</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Central African Republic</countryname>
			<code>CAFR</code>
			<observer>true</observer>
		</country>
		<country>
			<countryname>Chad</countryname>
			<code>CHAD</code>
			<observer>true</observer>
		</country>
		<country>
			<countryname>China</countryname>
			<code>CHIN</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Congo</countryname>
			<code>CONG</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>France</countryname>
			<code>FRAN</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Ghana</countryname>
			<code>GHAN</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Israel</countryname>
			<code>ISRA</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Italy</countryname>
			<code>ITAL</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Panama</countryname>
			<code>PANA</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Peru</countryname>
			<code>PERU</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Qatar</countryname>
			<code>QATA</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Russian Federation</countryname>
			<code>RUSS</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Slovak Republic</countryname>
			<code>SVKA</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>South Africa</countryname>
			<code>SOAF</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>Sudan</countryname>
			<code>SUDA</code>
			<observer>true</observer>
		</country>
		<country>
			<countryname>United Kingdom</countryname>
			<code>UNKG</code>
			<observer>false</observer>
		</country>
		<country>
			<countryname>United States of America</countryname>
			<code>UNST</code>
			<observer>false</observer>
		</country>
	</countries>
	<GSLtime>90</GSLtime>
	<topics>
		<topic>
			<topicname>Sudan and Chad</topicname>
		</topic>
		<topic>
			<topicname>The Weaponization of Outer Space</topicname>
		</topic>
	</topics>
</committee>
