<?xml version="1.0"?>
<!DOCTYPE countries [
  <!ELEMENT countries (country+) >
  <!ELEMENT country (name,code?,observer?) >
  <!ELEMENT name (#PCDATA) >
  <!ELEMENT code (#PCDATA) >
  <!ELEMENT observer (#PCDATA) >
]>
<countries>
	<country>
		<name>Afghanistan</name>
		<code>AFGH</code>
	</country>
	<country>
		<name>Albania</name>
		<code>ALBA</code>
	</country>
	<country>
		<name>Algeria</name>
		<code>ALGE</code>
	</country>
	<country>
		<name>Amnesty International</name>
		<code>AMIN</code>
		<observer>true</observer>
	</country>
	<country>
		<name>Andorra</name>
		<code>ANDR</code>
	</country>
	<country>
		<name>Angola</name>
		<code>ANGO</code>
	</country>
	<country>
		<name>Antigua and Barbuda</name>
		<code>ANTI</code>
	</country>
	<country>
		<name>Argentina</name>
		<code>ARGE</code>
	</country>
	<country>
		<name>Armenia</name>
		<code>ARME</code>
	</country>
	<country>
		<name>Australia</name>
		<code>ASTL</code>
	</country>
	<country>
		<name>Austria</name>
		<code>AUST</code>
	</country>
	<country>
		<name>Azerbaijan</name>
		<code>AZER</code>
	</country>
	<country>
		<name>Bahamas</name>
		<code>BHMS</code>
	</country>
	<country>
		<name>Bahrain</name>
		<code>BHRN</code>
	</country>
	<country>
		<name>Bangladesh</name>
		<code>BNGL</code>
	</country>
	<country>
		<name>Barbados</name>
		<code>BRBD</code>
	</country>
	<country>
		<name>Belarus</name>
		<code>BLRU</code>
	</country>
	<country>
		<name>Belgium</name>
		<code>BELG</code>
	</country>
	<country>
		<name>Belize</name>
		<code>BLZE</code>
	</country>
	<country>
		<name>Benin</name>
		<code>BNIN</code>
	</country>
	<country>
		<name>Bhutan</name>
		<code>BHUT</code>
	</country>
	<country>
		<name>Bolivia</name>
		<code>BLVA</code>
	</country>
	<country>
		<name>Bosnia and Herzegovina</name>
		<code>BOHE</code>
	</country>
	<country>
		<name>Botswana</name>
		<code>BOTS</code>
	</country>
	<country>
		<name>Brazil</name>
		<code>BRAZ</code>
	</country>
	<country>
		<name>Brunei Darussalam</name>
		<code>BRUN</code>
	</country>
	<country>
		<name>Bulgaria</name>
		<code>BULG</code>
	</country>
	<country>
		<name>Burkina Faso</name>
		<code>BUFA</code>
	</country>
	<country>
		<name>Burundi</name>
		<code>BURU</code>
	</country>
	<country>
		<name>Council on American-Islamic Relations</name>
		<code>CAIR</code>
		<observer>true</observer>
	</country>
        <country>
		<name>Cambodia</name>
		<code>CAMB</code>
	</country>
	<country>
		<name>Cameroon</name>
		<code>CAME</code>
	</country>
	<country>
		<name>Canada</name>
		<code>CANA</code>
	</country>
	<country>
		<name>Cape Verde</name>
		<code>CAVE</code>
	</country>
	<country>
		<name>Central African Republic</name>
		<code>CAFR</code>
	</country>
	<country>
		<name>Chad</name>
		<code>CHAD</code>
	</country>
	<country>
		<name>Chile</name>
		<code>CHIL</code>
	</country>
	<country>
		<name>China</name>
		<code>CHIN</code>
	</country>
	<country>
		<name>Colombia</name>
		<code>CLMB</code>
	</country>
	<country>
		<name>Comoros</name>
		<code>COMO</code>
	</country>
	<country>
		<name>Congo</name>
		<code>CONG</code>
	</country>
	<country>
		<name>Congo, Dem. Rep. of</name>
		<code>CODR</code>
	</country>
	<country>
		<name>Cook Islands</name>
		<code>CKIS</code>
	</country>
	<country>
		<name>Costa Rica</name>
		<code>CORC</code>
	</country>
	<country>
		<name>Cote d'Ivoire</name>
		<code>CDIV</code>
	</country>
	<country>
		<name>Croatia</name>
		<code>CROA</code>
	</country>
	<country>
		<name>Cuba</name>
		<code>CUBA</code>
	</country>
	<country>
		<name>Cyprus</name>
		<code>CYPR</code>
	</country>
	<country>
		<name>Czech Republic</name>
		<code>CZEC</code>
	</country>
	<country>
		<name>Democratic Yemen</name>
		<code>SOYM</code>
	</country>
	<country>
		<name>Denmark</name>
		<code>DENM</code>
	</country>
	<country>
		<name>Djibouti</name>
		<code>DJIB</code>
	</country>
	<country>
		<name>Dominica</name>
		<code>DOMN</code>
	</country>
	<country>
		<name>Dominican Republic</name>
		<code>DORE</code>
	</country>
	<country>
		<name>Ecuador</name>
		<code>ECUA</code>
	</country>
	<country>
		<name>Egypt</name>
		<code>EGYP</code>
	</country>
	<country>
		<name>El Salvador</name>
		<code>ELSA</code>
	</country>
	<country>
		<name>Equatorial Guinea</name>
		<code>EQGU</code>
	</country>
	<country>
		<name>Eritrea</name>
		<code>ERIT</code>
	</country>
	<country>
		<name>Estonia</name>
		<code>ESTN</code>
	</country>
	<country>
		<name>Ethiopia</name>
		<code>ETHP</code>
	</country>
	<country>
		<name>Fiji</name>
		<code>FIJI</code>
	</country>
	<country>
		<name>Finland</name>
		<code>FINL</code>
	</country>
	<country>
		<name>France</name>
		<code>FRAN</code>
	</country>
	<country>
		<name>Gabon</name>
		<code>GABN</code>
	</country>
	<country>
		<name>Gambia</name>
		<code>GAMB</code>
	</country>
	<country>
		<name>Georgia</name>
		<code>GEOR</code>
	</country>
	<country>
		<name>Germany</name>
		<code>GERM</code>
	</country>
	<country>
		<name>German Dem. Rep. (East)</name>
		<code>GERM</code>
	</country>
	<country>
		<name>Ghana</name>
		<code>GHAN</code>
	</country>
	<country>
		<name>Greece</name>
		<code>GREC</code>
	</country>
	<country>
		<name>Grenada</name>
		<code>GREN</code>
	</country>
	<country>
		<name>Guatemala</name>
		<code>GUAT</code>
	</country>
	<country>
		<name>Guinea</name>
		<code>GUIN</code>
	</country>
	<country>
		<name>Guinea-Bissau</name>
		<code>GUBA</code>
	</country>
	<country>
		<name>Guyana</name>
		<code>GUYA</code>
	</country>
	<country>
		<name>Haiti</name>
		<code>HAIT</code>
	</country>
	<country>
		<name>Holy See</name>
		<code>VACY</code>
		<observer>true</observer>
	</country>
	<country>
		<name>Honduras</name>
		<code>HOND</code>
	</country>
	<country>
		<name>Hungary</name>
		<code>HUNG</code>
	</country>
	<country>
		<name>Iceland</name>
		<code>ICEL</code>
	</country>
	<country>
		<name>India</name>
		<code>INDA</code>
	</country>
	<country>
		<name>Indonesia</name>
		<code>INDN</code>
	</country>
	<country>
		<name>Iran</name>
		<code>IRAN</code>
	</country>
	<country>
		<name>Iraq</name>
		<code>IRAQ</code>
	</country>
	<country>
		<name>Ireland</name>
		<code>IREL</code>
	</country>
	<country>
		<name>Israel</name>
		<code>ISRA</code>
	</country>
	<country>
		<name>Italy</name>
		<code>ITAL</code>
	</country>
	<country>
		<name>Jamaica</name>
		<code>JAMA</code>
	</country>
	<country>
		<name>Japan</name>
		<code>JAPA</code>
	</country>
	<country>
		<name>Jordan</name>
		<code>JORD</code>
	</country>
	<country>
		<name>Kazahkstan</name>
		<code>KAZK</code>
	</country>
	<country>
		<name>Kenya</name>
		<code>KENY</code>
	</country>
	<country>
		<name>Kiribati</name>
		<code>KIRB</code>
	</country>
	<country>
		<name>Korea, DPR (North)</name>
		<code>NKOR</code>
	</country>
	<country>
		<name>Korea, Rep. of (South)</name>
		<code>SKOR</code>
	</country>
	<country>
		<name>Kuwait</name>
		<code>KUWA</code>
	</country>
	<country>
		<name>Kyrgyzstan</name>
		<code>KYRG</code>
	</country>
	<country>
		<name>Lao PDR</name>
		<code>LAOS</code>
	</country>
	<country>
		<name>Latvia</name>
		<code>LATV</code>
	</country>
	<country>
		<name>Lebanon</name>
		<code>LEBA</code>
	</country>
	<country>
		<name>Lesotho</name>
		<code>LEST</code>
	</country>
	<country>
		<name>Liberia</name>
		<code>LIBE</code>
	</country>
	<country>
		<name>Libyan Arab Jamahiriya</name>
		<code>LBYA</code>
	</country>
	<country>
		<name>Liechtenstein</name>
		<code>LIEC</code>
	</country>
	<country>
		<name>Lithuania</name>
		<code>LITH</code>
	</country>
	<country>
		<name>Luxembourg</name>
		<code>LUXE</code>
	</country>
	<country>
		<name>Macedonia</name>
		<code>MACE</code>
	</country>
	<country>
		<name>Madagascar</name>
		<code>MADA</code>
	</country>
	<country>
		<name>Malawi</name>
		<code>MALW</code>
	</country>
	<country>
		<name>Malaysia</name>
		<code>MALS</code>
	</country>
	<country>
		<name>Maldives</name>
		<code>MALD</code>
	</country>
	<country>
		<name>Mali</name>
		<code>MALI</code>
	</country>
	<country>
		<name>Malta</name>
		<code>MALT</code>
	</country>
	<country>
		<name>Marshall Islands</name>
		<code>MAIS</code>
	</country>
	<country>
		<name>Mauritania</name>
		<code>MAUR</code>
	</country>
	<country>
		<name>Mauritius</name>
		<code>MRTS</code>
	</country>
	<country>
		<name>Mexico</name>
		<code>MEXC</code>
	</country>
	<country>
		<name>Micronesia</name>
		<code>MICR</code>
	</country>
	<country>
		<name>Moldova</name>
		<code>MOLD</code>
	</country>
	<country>
		<name>Monaco</name>
		<code>MONA</code>
	</country>
	<country>
		<name>Mongolia</name>
		<code>MONG</code>
	</country>
	<country>
		<name>Montenegro</name>
		<code>MNGR</code>
	</country>
	<country>
		<name>Morocco</name>
		<code>MORC</code>
	</country>
	<country>
		<name>Mozambique</name>
		<code>MOZA</code>
	</country>
	<country>
		<name>Myanmar</name>
		<code>MYAN</code>
	</country>
	<country>
		<name>Namibia</name>
		<code>NAMB</code>
	</country>
	<country>
		<name>Nauru</name>
		<code>NAUR</code>
	</country>
	<country>
		<name>Nepal</name>
		<code>NEPA</code>
	</country>
	<country>
		<name>Netherlands</name>
		<code>NETH</code>
	</country>
	<country>
		<name>New Zealand</name>
		<code>NWZE</code>
	</country>
	<country>
		<name>Nicaragua</name>
		<code>NICA</code>
	</country>
	<country>
		<name>Niger</name>
		<code>NIGR</code>
	</country>
	<country>
		<name>Nigeria</name>
		<code>NGRA</code>
	</country>
	<country>
		<name>Niue</name>
		<code>NIUE</code>
	</country>
	<country>
		<name>Norway</name>
		<code>NORW</code>
	</country>
	<country>
		<name>Oman</name>
		<code>OMAN</code>
	</country>
	<country>
		<name>Pakistan</name>
		<code>PAKS</code>
	</country>
	<country>
		<name>Palau</name>
		<code>PALA</code>
	</country>
	<country>
		<name>Palestine</name>
		<code>WEBA</code>
		<observer>true</observer>
	</country>
	<country>
		<name>Panama</name>
		<code>PANA</code>
	</country>
	<country>
		<name>Papua New Guinea</name>
		<code>PANG</code>
	</country>
	<country>
		<name>Paraguay</name>
		<code>PARA</code>
	</country>
	<country>
		<name>Peru</name>
		<code>PERU</code>
	</country>
	<country>
		<name>Philippines</name>
		<code>PHIL</code>
	</country>
	<country>
		<name>Poland</name>
		<code>POLA</code>
	</country>
	<country>
		<name>Portugal</name>
		<code>PORT</code>
	</country>
	<country>
		<name>Qatar</name>
		<code>QATA</code>
	</country>
	<country>
		<name>Romania</name>
		<code>RMNA</code>
	</country>
	<country>
		<name>Russian Federation</name>
		<code>RUSS</code>
	</country>
	<country>
		<name>Rwanda</name>
		<code>RWAN</code>
	</country>
	<country>
		<name>Samoa</name>
		<code>SAMO</code>
	</country>
	<country>
		<name>San Marino</name>
		<code>SAMA</code>
	</country>
	<country>
		<name>Sao Tome and Principe</name>
		<code>STPR</code>
	</country>
	<country>
		<name>Saudi Arabia</name>
		<code>SAAR</code>
	</country>
	<country>
		<name>Senegal</name>
		<code>SENE</code>
	</country>
	<country>
		<name>Serbia</name>
		<code>SERB</code>
	</country>
	<country>
		<name>Seychelles</name>
		<code>SEYC</code>
	</country>
	<country>
		<name>Sierra Leone</name>
		<code>SILE</code>
	</country>
	<country>
		<name>Singapore</name>
		<code>SING</code>
	</country>
	<country>
		<name>Slovak Republic</name>
		<code>SVKA</code>
	</country>
	<country>
		<name>Slovenia</name>
		<code>SLVA</code>
	</country>
	<country>
		<name>Solomon Islands</name>
		<code>SOIS</code>
	</country>
	<country>
		<name>Somalia</name>
		<code>SMLA</code>
	</country>
	<country>
		<name>South Africa</name>
		<code>SOAF</code>
	</country>
	<country>
		<name>Spain</name>
		<code>SPAN</code>
	</country>
	<country>
		<name>Sri Lanka</name>
		<code>SRLA</code>
	</country>
	<country>
		<name>St. Kitts and Nevis</name>
		<code>STKN</code>
	</country>
	<country>
		<name>St. Lucia</name>
		<code>STLU</code>
	</country>
	<country>
		<name>St. Vincent and the Grenadines</name>
		<code>SVGR</code>
	</country>	
	<country>
		<name>Sudan</name>
		<code>SUDA</code>
	</country>
	<country>
		<name>Suriname</name>
		<code>SURN</code>
	</country>
	<country>
		<name>Swaziland</name>
		<code>SZLD</code>
	</country>
	<country>
		<name>Sweden</name>
		<code>SWDN</code>
	</country>
	<country>
		<name>Switzerland</name>
		<code>SWIT</code>
	</country>
	<country>
		<name>Syrian Arab Republic</name>
		<code>SYRA</code>
	</country>
	<country>
		<name>Tajikistan</name>
		<code>TAJK</code>
	</country>
	<country>
		<name>Thailand</name>
		<code>THAL</code>
	</country>
	<country>
		<name>Timor-Leste</name>
		<code>ETIM</code>
	</country>
	<country>
		<name>Togo</name>
		<code>TOGO</code>
	</country>
	<country>
		<name>Tonga</name>
		<code>TONG</code>
	</country>
	<country>
		<name>Trinidad and Tobago</name>
		<code>TRTB</code>
	</country>
	<country>
		<name>Tunisia</name>
		<code>TUNS</code>
	</country>
	<country>
		<name>Turkey</name>
		<code>TURK</code>
	</country>
	<country>
		<name>Turkmenistan</name>
		<code>TKST</code>
	</country>
	<country>
		<name>Tuvalu</name>
		<code>TUVA</code>
	</country>
	<country>
		<name>Uganda</name>
		<code>UGAN</code>
	</country>
	<country>
		<name>Ukraine</name>
		<code>UKRN</code>
	</country>
	<country>
		<name>United Arab Emirates</name>
		<code>UAEM</code>
	</country>
	<country>
		<name>United Kingdom</name>
		<code>UNKG</code>
	</country>
	<country>
		<name>United Republic of Tanzania</name>
		<code>TANZ</code>
	</country>
	<country>
		<name>United States of America</name>
		<code>UNST</code>
	</country>
	<country>
		<name>Uruguay</name>
		<code>URGY</code>
	</country>
	<country>
		<name>Uzbekistan</name>
		<code>UZBK</code>
	</country>
	<country>
		<name>Vanuatu</name>
		<code>VANT</code>
	</country>
	<country>
		<name>Venezuela</name>
		<code>VENZ</code>
	</country>
	<country>
		<name>Vietnam</name>
		<code>VIET</code>
	</country>
	<country>
		<name>Yemen</name>
		<code>YEMN</code>
	</country>
	<country>
		<name>Zambia</name>
		<code>ZAMB</code>
	</country>
	<country>
		<name>Zimbabwe</name>
		<code>ZBWE</code>
	</country>
</countries>
